#+STARTUP: overview



* Transient notes
** Debugger debugger

#+begin_example
---------------------------
Microsoft Visual Studio
---------------------------
Unable to start program 'C:\tom\github\raddebugger_build\build\vs2019\x64\debug\raddebugger_build'.

Access is denied.

---------------------------
OK   
---------------------------
#+end_example

** Window placement

"Just" store WINDOWPLACEMENT in config file. Serialize as binary
string like b2. If anything goes wrong, Windows will deal with it.
Worst case: the window doesn't end up where you expect.

Can get rid of most of the existing functions. Only
=os_dim_from_monitor= remains vaguely relevant, best replaced with
=os_dim_from_primary_monitor= for filling in defaults if no
WINDOWPLACEMENT available.

//internal OS_HandleArray os_push_monitors_array(Arena *arena);
//internal OS_Handle      os_primary_monitor(void);
//internal OS_Handle      os_monitor_from_window(OS_Handle window);
//internal String8        os_name_from_monitor(Arena *arena, OS_Handle monitor);
//internal Vec2F32        os_dim_from_monitor(OS_Handle monitor);
//internal B32            os_window_is_maximized(OS_Handle window);
//internal void           os_window_set_monitor(OS_Handle window, OS_Handle monitor);


*** os_ functions

**** =OS_HandleArray os_push_monitors_array(Arena *arena);=

Used to map monitor name to monitor.

**** =OS_Handle      os_primary_monitor(void);=

Used to fill in defaults.

**** =OS_Handle      os_monitor_from_window(OS_Handle window);=

Used when saving window config.

**** =String8        os_name_from_monitor(Arena *arena, OS_Handle monitor);=

Used when saving window config.

**** =Vec2F32        os_dim_from_monitor(OS_Handle monitor);=

Used to fill in defaults.

** Fails to debug debug b2

Call stack for start of =main=

#+begin_example
  b2.exe!SDL_main(int argc=1, char * * argv=0x00000239e043e480) Line 1609	C++
  b2.exe!main_getcmdline() Line 80	C
  b2.exe!main(int argc=1, char * * argv=0x00000239e042c740) Line 95	C
  b2.exe!invoke_main() Line 79	C++
  b2.exe!__scrt_common_main_seh() Line 288	C++
  b2.exe!__scrt_common_main() Line 331	C++
  b2.exe!mainCRTStartup(void * __formal=0x0000004ea8db5000) Line 17	C++
  kernel32.dll!BaseThreadInitThunk()	Unknown
  ntdll.dll!RtlUserThreadStart()	Unknown
#+end_example

Note entry points list in =DEMON_EventKind_HandshakeComplete= and
presence in b2 debug:

| Entry point          | Console | Gui |
|----------------------+---------+-----|
| =WinMain=            |   y     | y   |
| =wWinMain=           |         |     |
| =main=               |   y     | y   |
| =wmain=              |   y     | y   |
| =WinMainCRTStartup=  |         |  y  |
| =wWinMainCRTStartup= |         |     |
| =mainCRTStartup=     |   y     |     |
| =wmainCRTStartup=    |         |     |

As b2 builds for all startup types, it will have multiple entry
points.

* eof.
